matrix:
  include:
    - os: linux
      dist: trusty
      language: android
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-28
          # - sys-img-armeabi-v7a-google_apis-25
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-android-support
      jdk: openjdk11
      sudo: false
      addons:
        apt:
          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
          sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
          packages:
            - libstdc++6
      install:
        - mkdir -p $HOME/wgetcache
        - cd $HOME
        - |
          if [ ! -e $HOME/wgetcache/flutter_linux_v1.7.8+hotfix.4-stable.tar.xz ]; then
            wget https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.7.8+hotfix.4-stable.tar.xz -P $HOME/wgetcache
            yes -y | rm -rf flutter
            tar xf wgetcache/flutter_linux_v1.7.8+hotfix.4-stable.tar.xz
            ./flutter/bin/flutter precache
          fi
        - export PATH="$PATH:`pwd`/flutter/bin"
        - cd -
        - pwd

      script:
        - pwd
        - flutter doctor
        - |
          COMMIT_MSG=`git show -s --format=%B HEAD`
          if [ "$COMMIT_MSG" = "update flutter" ]; then 
            flutter upgrade
          fi;
        - |
          output=$(dartfmt ./ -n)
          if [ ! -z $output]; then
            exit 1
          fi;
        - flutter test
        - cd example
        - flutter -v build apk
        - flutter test

    - os: osx
      language: generic
      osx_image: xcode10.2
      install:
        - pip install six
        - brew update
        - |
          if brew ls --versions libimobiledevice > /dev/null; then
            brew uninstall --ignore-dependencies libimobiledevice
          fi
        - |
          if brew ls --versions usbmuxd > /dev/null; then
            brew uninstall --ignore-dependencies usbmuxd
          fi
        - brew install --HEAD usbmuxd
        - brew unlink usbmuxd
        - brew link usbmuxd
        - brew install --HEAD libimobiledevice
        - brew install ideviceinstaller
        - brew install ios-deploy
        - cd $HOME
        - |
          if [ ! -e $HOME/wgetcache/flutter_macos_v1.7.8+hotfix.4-stable.zip ]; then
            wget https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_v1.7.8+hotfix.4-stable.zip -P $HOME/wgetcache
            yes -y | rm -rf flutter
            unzip -qq wgetcache/flutter_macos_v1.7.8+hotfix.4-stable.zip
            ./flutter/bin/flutter precache
          fi
        - export PATH="$PATH:`pwd`/flutter/bin"
        - cd -
        - pwd

      script:
        - pwd
        - flutter doctor
        - |
          COMMIT_MSG=`git show -s --format=%B HEAD`
          if [ "$COMMIT_MSG" = "update flutter" ]; then 
            flutter upgrade
          fi;
        - |
          output=$(dartfmt ./ -n)
          if [ ! -z $output]; then
            exit 1
          fi;
        - pod repo update
        - flutter test
        - cd example
        - cd ios && pod install &&cd -
        - flutter -v build ios --no-codesign
        - flutter test
        - cd -

cache:
  directories:
    - $HOME/.gradle/wrapper/
    - $HOME/.pub-cache
    - $HOME/wgetcache
    - $HOME/flutter

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
